# Generated by Django 4.2.1 on 2025-04-14 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pojistenec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Jméno')),
                ('last_name', models.CharField(max_length=50, verbose_name='Příjmení')),
                ('address_street', models.CharField(max_length=50, verbose_name='Ulice')),
                ('address_city', models.CharField(max_length=50, verbose_name='Město')),
                ('psc', models.CharField(max_length=6, verbose_name='PSČ')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Pojisteni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=50, verbose_name='Typ pojištění')),
                ('predmet', models.CharField(max_length=100, verbose_name='Předmět pojištění')),
                ('castka', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Částka')),
                ('platnost_od', models.DateField(verbose_name='Platnost od')),
                ('platnost_do', models.DateField(verbose_name='Platnost do')),
                ('pojistenec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pojisteni', to='pojistenci.pojistenec')),
            ],
        ),
    ]
