# Generated by Django 4.2.1 on 2025-04-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojistenci', '0002_alter_pojistenec_email_alter_pojistenec_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojisteni',
            name='typ',
            field=models.CharField(choices=[('Úrazové', 'Úrazové'), ('Cestovní', 'Cestovní'), ('Majetkové', 'Pojištění majetku')], max_length=50, verbose_name='Typ pojištění'),
        ),
    ]
