# Generated by Django 4.2.1 on 2025-04-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojistenci', '0003_alter_pojisteni_typ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojisteni',
            name='typ',
            field=models.CharField(choices=[('Úrazové', 'Úrazové'), ('Cestovní', 'Cestovní'), ('Majetkové', 'Pojištění majetku')], default='Cestovní', max_length=50, verbose_name='Typ pojištění'),
        ),
    ]
