# Generated by Django 4.2.1 on 2025-04-24 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pojistenci', '0004_alter_pojisteni_typ'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypPojisteni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=30, unique=True, verbose_name='Typ Pojištění')),
            ],
        ),
        migrations.AlterField(
            model_name='pojisteni',
            name='typ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pojistenci.typpojisteni', verbose_name='Typ pojištění'),
        ),
    ]
