# Generated by Django 4.2.1 on 2025-04-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojistenci', '0005_typpojisteni_alter_pojisteni_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='pojistenec',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotky_pojistencu/', verbose_name='Fotografie'),
        ),
    ]
