# Generated by Django 4.2.1 on 2025-04-28 15:53

import django.core.validators
from django.db import migrations, models
import pojistenci.models


class Migration(migrations.Migration):

    dependencies = [
        ('pojistenci', '0006_pojistenec_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojistenec',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotky_pojistencu/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), pojistenci.models.validate_image_size], verbose_name='Fotografie'),
        ),
        migrations.AlterField(
            model_name='typpojisteni',
            name='nazev',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Typ Pojištění'),
        ),
    ]
