# Generated by Django 4.2.1 on 2026-03-07 21:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import pojistenci.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pojistenci', '0008_contact_emailtemplate_emailcampaign_emaildelivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Název')),
                ('image', models.ImageField(upload_to='email_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), pojistenci.models.validate_email_image_size], verbose_name='Obrázek')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Velikost souboru (B)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Nahráno')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Nahrál')),
            ],
            options={
                'verbose_name': 'Obrázek do emailu',
                'verbose_name_plural': 'Obrázky do emailu',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
