# Generated by Django 4.2.1 on 2026-03-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojistenci', '0009_emailimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Název skupiny')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Skupina kontaktů',
                'verbose_name_plural': 'Skupiny kontaktů',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='contacts', to='pojistenci.contactgroup', verbose_name='Skupiny'),
        ),
    ]
