# Generated by Django 4.2.1 on 2026-03-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojistenci', '0010_contactgroup_contact_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='salutation',
            field=models.CharField(blank=True, help_text="Oslovení (např. 'Vážený pane Nováku')", max_length=100, verbose_name='Oslovení'),
        ),
    ]
