# Generated by Django 4.2.1 on 2026-03-12 09:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pojistenci', '0011_contact_salutation'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='unsubscribe_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
