# Generated by Django 4.2.1 on 2026-03-12 09:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pojistenci', '0012_contact_unsubscribe_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='unsubscribe_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
