# Generated by Django 4.2.1 on 2026-03-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojistenci', '0014_emaildelivery_click_count_emaildelivery_clicked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailclickevent',
            name='is_suspected_bot',
            field=models.BooleanField(default=False),
        ),
    ]
