# Generated by Django 4.2.1 on 2026-03-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojistenci', '0015_emailclickevent_is_suspected_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailclickevent',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emaildelivery',
            name='unique_click_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
