# Generated by Django 4.2.1 on 2026-03-14 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pojistenci', '0016_emailclickevent_is_duplicate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildelivery',
            name='tracking_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.CreateModel(
            name='EmailCampaignTrackedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_links', to='pojistenci.emailcampaign')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('campaign', 'url')},
            },
        ),
    ]
