# Generated by Django 4.2.1 on 2026-03-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojistenci', '0017_alter_emaildelivery_tracking_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildelivery',
            name='tracking_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, unique=True),
        ),
    ]
