# Generated by Django 4.2.1 on 2026-03-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojistenci', '0018_alter_emaildelivery_tracking_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='preheader',
            field=models.CharField(blank=True, help_text='Krátký text zobrazovaný jako náhled emailu v inboxu', max_length=200),
        ),
    ]
