# Generated by Django 4.2.1 on 2026-03-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojistenci', '0019_emailtemplate_preheader'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='preheader',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
