from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .views import VlastniLoginView


urlpatterns = [
    path('', views.index, name='homepage'),
    path('pojistenci', views.pojistenci_vypis, name='pojistenci'),
    path('pojistenci/<int:id>', views.pojistenec_detail, name='pojistenec_detail'),
    path('pojistenci/novy_pojistenec', views.novy_pojistenec, name='novy_pojistenec'),
    path('pojistenci/smazat/<int:pojistenec_id>', views.smaz_pojistence, name='smazat-pojistence'),
    path('pojistenci/upravit/<int:pojistenec_id>', views.uprav_pojistence, name='uprav-pojistence'),
    path('pojistenci/smazat/<int:pojistenec_id>/pojisteni/pridat', views.pridat_pojisteni, name='pridat_pojisteni'),
    path('pojisteni', views.pojisteni_vypis, name='pojisteni-vypis'),
    path('pojisteni/smazat/<int:typ_pojisteni_id>', views.smaz_typ_pojisteni, name='smazat-typ-pojisteni'), 
    path('pojisteni/upravit/<int:pojisteni_id>', views.uprav_pojisteni, name='uprav-pojisteni'),
    path('pojisteni/delete/<int:pojisteni_id>', views.smaz_pojisteni, name='smazat-pojisteni'),
    path('pojisteni/<int:pojisteni_id>', views.pojisteni_detail, name='pojisteni_detail'),
    path('pojisteni/typ-pojisteni', views.typ_pojisteni, name='pridej-typ-pojisteni'),
    path('login/', VlastniLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
    path('registrace/', views.registrace, name='registrace'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name="pojistenci/password_reset_form.html", email_template_name="pojistenci/password_reset_email.html", subject_template_name="pojistenci/password_reset_subject.txt", success_url="done/",), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name="pojistenci/password_reset_done.html"), name="password_reset_done"),
    path("reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(template_name="pojistenci/password_reset_confirm.html", success_url="/password-reset/complete/"), name="password_reset_confirm"),
    path("password-reset/complete/", auth_views.PasswordResetCompleteView.as_view(template_name="pojistenci/password_reset_complete.html"), name="password_reset_complete"),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('pojistenci/import/', views.bulk_upload_pojistenci, name='bulk-upload-pojistenci'),
    path('pojistenci/vypis-api', views.vypis_api, name='vypis-api'),
    path('pojistenci/o_aplikaci', views.o_aplikaci, name='o-aplikaci'),
    path('pojistenci/vychytavky', views.vychytavky, name='vychytavky'),
    path('pojistenci/vychytavky/qr', views.generate_qr, name='generate-qr'),
    path('pojistenci/vychytavky/chart', views.generate_chart, name='generate-chart'),
    path('pojistenci/vychytavky/background', views.remove_background, name='remove-background'),
    path('pojistenci/vychytavky/pie-chart', views.generate_pie_chart, name='generate-pie-chart'),
    path('pojistenci/vychytavky/password-generator', views.generate_password, name='password-generator'),
    path('pojistenci/vychytavky/grouped-bar', views.generate_grouped_bar, name='generate-grouped-bar'),
    path('pojistenci/vychytavky/bar-chart', views.generate_bar_chart, name='generate-bar-chart'),
    path('pojistenci/vychytavky/csv-to-xlsx', views.convert_csv_to_xlsx, name='csv-to-xlsx'),
    path("pojistenci/vychytavky/rozesilac/", views.rozesilac_dashboard, name="rozesilac_dashboard"),
    path("pojistenci/vychytavky/rozesilac/sablony/", views.rozesilac_templates, name="rozesilac_templates"),
    path("pojistenci/vychytavky/rozesilac/sablony/nova/", views.rozesilac_template_create, name="rozesilac_template_create"),
    path("pojistenci/vychytavky/rozesilac/sablony/<int:template_id>/upravit/", views.rozesilac_template_edit, name="rozesilac_template_edit"),
    path("pojistenci/vychytavky/rozesilac/sablony/<int:template_id>/smazat/", views.rozesilac_template_delete, name="rozesilac_template_delete"),
    path("pojistenci/vychytavky/rozesilac/kontakty/", views.rozesilac_contacts, name="rozesilac_contacts"),
    path("pojistenci/vychytavky/rozesilac/kontakty/<int:contact_id>/upravit/", views.rozesilac_contact_edit, name="rozesilac_contact_edit"),
    path("pojistenci/vychytavky/rozesilac/odeslat/", views.rozesilac_send, name="rozesilac_send"),
    path("pojistenci/vychytavky/rozesilac/kampane/<int:campaign_id>/", views.rozesilac_campaign_detail, name="rozesilac_campaign_detail"),
    path("pojistenci/vychytavky/rozesilac/kampane/", views.rozesilac_campaigns, name="rozesilac_campaigns"),
    path("pojistenci/vychytavky/rozesilac/obrazky/", views.rozesilac_images, name="rozesilac_images"),
    path("pojistenci/vychytavky/rozesilac/obrazky/upload/", views.rozesilac_image_upload, name="rozesilac_image_upload"),
]
